### ISSUE TITLE
Materialized views for Cassandra

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/analysers#5]
As soon as we will move to Cassandra 3 (see https://github.com/benchflow/data-transformers/issues/16), we should add Materialized views to our [Cassandra database](https://github.com/benchflow/data-transformers/issues/6). The views should be added according to the [analysers](https://github.com/benchflow/analysers) requirements.

**Comment by Cerfoglg** [comment]
@VincenzoFerme Given our current solution, we don't need to introduce materialized views in our schema. Materialized views are something that would be needed if we had to query columns families without specifying their partition key, as it would be a great improvement in performance. But our current schema already partitions column families based primarily on their trial ID, experiment ID and container ID, and since we compute metrics over certain trials, experiments and containers, we always specify the partition key when querying Cassandra for the data.

**Comment by VincenzoFerme** [comment]
I agree.

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, since we settled on a solution now
